import type { ReadOnlyDb } from './readonly'
import { parseSince, parseUntil } from './dates'

/** Read-only access to AI memory, the cached AI analysis and the action log. */

function clampInt(value: number | undefined, def: number, min: number, max: number): number {
  const n = Number.isFinite(value) ? Math.floor(value as number) : def
  return Math.min(max, Math.max(min, n))
}

// Undo/redo payloads can be large: lower page size when they are included.
export const ACTION_LOG_MAX_LIMIT = 500
export const ACTION_LOG_PAYLOAD_DEFAULT_LIMIT = 20
export const ACTION_LOG_PAYLOAD_MAX_LIMIT = 50

export async function getAiMemory(db: ReadOnlyDb): Promise<{ memory: string; updatedAt: string | null }> {
  const { data, error } = await db
    .from('user_ai_memory')
    .select('memory_text, updated_at')
    .limit(1)
    .maybeSingle()
  if (error) throw new Error(`Errore lettura memoria AI: ${error.message}`)
  const row = data as { memory_text: string | null; updated_at: string | null } | null
  return { memory: row?.memory_text ?? '', updatedAt: row?.updated_at ?? null }
}

export interface AiAnalysisInfo {
  analysis: string | null
  firstGeneratedAt: string | null
  lastGeneratedAt: string | null
  lastAutoGeneratedAt: string | null
}

export async function getAiAnalysis(db: ReadOnlyDb): Promise<AiAnalysisInfo> {
  const { data, error } = await db
    .from('ai_analysis')
    .select('analysis_text, first_generation_time, last_generation_time, last_auto_generation_time')
    .limit(1)
    .maybeSingle()
  if (error) throw new Error(`Errore lettura analisi AI: ${error.message}`)
  const row = data as {
    analysis_text: string | null
    first_generation_time: string | null
    last_generation_time: string | null
    last_auto_generation_time: string | null
  } | null
  return {
    analysis: row?.analysis_text ?? null,
    firstGeneratedAt: row?.first_generation_time ?? null,
    lastGeneratedAt: row?.last_generation_time ?? null,
    lastAutoGeneratedAt: row?.last_auto_generation_time ?? null,
  }
}

export interface ActionLogFilters {
  type?: string
  since?: string
  until?: string
  includeCancelled?: boolean
  includePayload?: boolean
  limit?: number
  offset?: number
}

export interface ActionLogItem {
  id: string
  createdAt: string
  type: string
  label: string
  isCancelled: boolean
  undoData?: unknown
  redoData?: unknown
}

export async function listActionLog(
  db: ReadOnlyDb,
  filters: ActionLogFilters = {},
): Promise<{ total: number; items: ActionLogItem[] }> {
  const includeCancelled = filters.includeCancelled ?? true
  const includePayload = filters.includePayload ?? false
  const limit = includePayload
    ? clampInt(filters.limit, ACTION_LOG_PAYLOAD_DEFAULT_LIMIT, 1, ACTION_LOG_PAYLOAD_MAX_LIMIT)
    : clampInt(filters.limit, 50, 1, ACTION_LOG_MAX_LIMIT)
  const offset = clampInt(filters.offset, 0, 0, Number.MAX_SAFE_INTEGER)
  // Date-only values are whole days in Europe/Rome (until = through the end of that day).
  const sinceMs = parseSince(filters.since)
  const untilBound = parseUntil(filters.until)
  const since = sinceMs !== undefined ? new Date(sinceMs).toISOString() : undefined
  const until = untilBound ? new Date(untilBound.ms).toISOString() : undefined

  const columns = includePayload
    ? 'id, created_at, type, label, is_cancelled, undo_data, redo_data'
    : 'id, created_at, type, label, is_cancelled'

  let q = db.from('action_logs').select(columns, { count: 'exact' })
  if (filters.type) q = q.eq('type', filters.type)
  if (since) q = q.gte('created_at', since)
  if (until) q = untilBound!.exclusive ? q.lt('created_at', until) : q.lte('created_at', until)
  if (!includeCancelled) q = q.or('is_cancelled.is.null,is_cancelled.eq.false')

  const { data, error, count } = await q
    .order('created_at', { ascending: false })
    .order('id', { ascending: false })
    .range(offset, offset + limit - 1)
  if (error) throw new Error(`Errore lettura registro azioni: ${error.message}`)

  const rows = (data ?? []) as unknown as {
    id: string
    created_at: string
    type: string
    label: string
    is_cancelled: boolean | null
    undo_data?: unknown
    redo_data?: unknown
  }[]

  return {
    total: count ?? rows.length,
    items: rows.map(r => {
      const item: ActionLogItem = {
        id: r.id,
        createdAt: r.created_at,
        type: r.type,
        label: r.label,
        isCancelled: Boolean(r.is_cancelled),
      }
      if (includePayload) {
        item.undoData = r.undo_data ?? null
        item.redoData = r.redo_data ?? null
      }
      return item
    }),
  }
}
